name: Terraform Three Tier Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform Action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform AWS
    runs-on: ubuntu-latest

    steps:

      # --------------------------------------------------
      # 1. Checkout repository
      # --------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # --------------------------------------------------
      # 2. Setup Terraform
      # --------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # --------------------------------------------------
      # 3. Configure AWS using GitHub OIDC
      # --------------------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # --------------------------------------------------
      # 4. Verify AWS authentication
      # --------------------------------------------------
      - name: Verify AWS Identity
        run: |
          echo "AWS Region: ${{ secrets.AWS_REGION }}"
          aws sts get-caller-identity

      # --------------------------------------------------
      # 5. Check Terraform version
      # --------------------------------------------------
      - name: Terraform Version
        run: terraform version

      # --------------------------------------------------
      # 7. Terraform Init
      # --------------------------------------------------
      - name: Terraform Init
        run: terraform init

      # --------------------------------------------------
      # 8. Terraform Validate
      # --------------------------------------------------
      - name: Terraform Validate
        run: terraform validate

      # --------------------------------------------------
      # 9. Show Terraform Providers
      # --------------------------------------------------
      - name: Terraform Providers
        run: terraform providers

      # --------------------------------------------------
      # 10. Terraform Plan
      # --------------------------------------------------
      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -no-color \
            -out=tfplan

      # --------------------------------------------------
      # 11. Terraform Apply
      # --------------------------------------------------
      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: |
          terraform apply \
            -input=false \
            -auto-approve \
            tfplan

      # --------------------------------------------------
      # 12. Terraform Destroy
      # --------------------------------------------------
      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: |
          terraform destroy \
            -input=false \
            -auto-approve \
            -no-color
